name: Metrics
on:
  schedule: [{cron: "0 */24 * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate main metrics badge
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Generate achievements metrics badge
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          base_indepth: yes
          plugin_achievements: yes
          repositories_affiliations: owner
          plugin_achievements_secrets: true
          filename: metrics.achievements.svg
          plugin_achievements_display: compact

      - name: Generate language metrics badge
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base_indepth: yes
          base: ''
          plugin_languages: yes
          repositories_affiliations: owner, collaborator, organization-member
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 0
          filename: metrics.languages.svg
          plugin_languages_colors: rainbow
          plugin_languages_ignored: html, css, php, c++
